# Generated by Django 2.1.7 on 2019-03-29 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_agendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenda_institucional',
            name='nomeC',
        ),
        migrations.RemoveField(
            model_name='agenda_publica',
            name='nomeCompromisso',
        ),
        migrations.AddField(
            model_name='agenda_institucional',
            name='nome',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nome do compromisso:'),
        ),
        migrations.AddField(
            model_name='agenda_institucional',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nome do usuário:'),
        ),
        migrations.AddField(
            model_name='agenda_publica',
            name='nome',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Nome do compromisso:'),
        ),
        migrations.AddField(
            model_name='agenda_publica',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nome do usuário:'),
        ),
    ]
